const Sr = require('../models/SalaryRaise')
const Bonus = require('../models/Bonus')
const Loan = require('../models/Loan')
const LoanNote = require('../models/LoanNote')
const Penalty = require('../models/Penalty')